### ISSUE TITLE
Include custom error handling in GitHub connector

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-incubator/hack-showcase#21]
**DESCRIPTION**
It is necessary to handle errors that can occur during runtime of existing structure of the connector.

**AC**
- [x] Think about the possible error cases
- [x] Design of error handling and messaging structure
- [x] Application of error handling in all reasonable places

**Comment by ksputo** [comment]
This will be discussed at the beginning of Sprint #2 and break into smaller, better described tasks.
