### ISSUE TITLE
Prepare Github Connector 0.2.0 release

### ISSUE THREAD

**Issue by ksputo** [kyma-incubator/hack-showcase#61]
**Description**
In order to document our progress, we want every sprint review demo to be available as release on our repository. This requires creating a description with links to PRs covered in this particular release and publishing the release it on repository

**AC**
- [x] Complete release description
- [x] Release v0.2.0 available on repository

**Comment by colunira** [comment]
Release available [here](https://github.com/kyma-incubator/hack-showcase/releases/tag/v0.2.0-demo)
