### ISSUE TITLE
Register application (GitHub) in APP Registry 

### ISSUE THREAD

**Issue by wojpon** [kyma-incubator/hack-showcase#7]
**DESCRIPTION**
In order to use application in Kyma ecosystem we need to register our app in Application Registry Component. To achieve this we need to create Application CR. 

**AC**
- [x] Create Application CR
- [x] Add Application to helm chart
- [x] Create json to register service
- [x] Send json with POST to Application Registry
- [x] Ask PB how to create Application CR (go, helm chart, client?)

**Comment by colunira** [comment]
Question to PB: How do we have to install GitHub Connector?
Answer: For future we want it to be installed through Kyma add-ons (bundles needed), but for now you can use simple helm chart, it can be done manually, so don't focus on installation process, make something working.
